version: '3'

services:
  namenode:
    image: fruitjeus/hadoop:latest
    hostname: namenode
    ports:
      - "9870:9870"
      - "8088:8088"
    volumes:
      - namenode:/hadoop/dfs
    command: >
      bash -c "hdfs namenode & hdfs datanode & yarn resourcemanager & yarn nodemanager & yarn historyserver "

  datanode:
    image: fruitjeus/hadoop:latest
    hostname: datanode
    depends_on:
      - namenode
    command: >
      bash -c "hdfs secondarynamenode & hdfs datanode & yarn nodemanager "
    ports:
      - "9868:9868"
      - "9864:9864"
    volumes:
      - datanode:/hadoop/dfs
volumes:
  namenode: {}
  datanode: {}

