version: '3'

services:
  master:
    image: fruitjeus/hadoop:latest
    hostname: master
    ports:
      - "9870:9870"
      - "8030:8030"
      - "8032:8032"
      - "8042:8042"
      - "8088:8088"
      - "8188:8188"
      - "9000:9000"
      - "18080:18080"
      - "19888:19888"
      - "19866:9866"
      - "19868:9868"
      - "19864:9864"
    volumes:
      - master:/hadoop/dfs
    command: >
      bash -c "(hdfs namenode & hdfs datanode & yarn resourcemanager & yarn nodemanager & yarn timelineserver &) && (sleep 20; hdfs dfs -mkdir /spark-logs; start-history-server.sh) "

  worker:
    image: fruitjeus/hadoop:latest
    hostname: worker
    depends_on:
      - master
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
      - "18042:8042"
      - "9866:9866"
      - "9868:9868"
      - "9864:9864"
    volumes:
      - worker:/hadoop/dfs
volumes:
  master: {}
  worker: {}

