version: '3'

services:
  namenode:
    image: fruitjeus/hadoop:latest
    hostname: namenode
    ports:
      - "9870:9870"
      - "8030:8030"
      - "8032:8032"
      - "8088:8088"
      - "8188:8188"
      - "9000:9000"
      - "18080:18080"
      - "19888:19888"
    volumes:
      - namenode:/hadoop/dfs
    command: >
      bash -c "(hdfs namenode & yarn resourcemanager & yarn nodemanager & yarn timelineserver &) && (sleep 20; hdfs dfs -mkdir /spark-logs; start-history-server.sh) "

  datanode:
    image: fruitjeus/hadoop:latest
    hostname: datanode
    depends_on:
      - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
      - "9866:9866"
      - "9868:9868"
      - "9864:9864"
    volumes:
      - datanode:/hadoop/dfs
volumes:
  namenode: {}
  datanode: {}

